version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    ignore:
      - dependency-name: "NUnit"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: monthly
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
