name: Test
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
    tags-ignore:
      - 'v*' #avoids rerun existing commit on release
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['netcoreapp3.1', 'net5.0' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x' #${{ matrix.dotnet-version }}
      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '5.0.x' #${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Run test from project
        run: |
          dotnet build TestProcess/TestProcess.csproj
          dotnet test --framework ${{ matrix.dotnet-version }} --logger "trx;LogFileName=../../reports/nunit/dotnet-background-report.trx" TestDotnetBackground/TestDotnetBackground.csproj

      - name: Run test from commandline
        if: always()
        run: |
          dotnet new tool-manifest
          dotnet pack DotnetBackground/DotnetBackground.csproj
          dotnet tool install --no-cache --add-source DotnetBackground/nupkg DotnetBackground
          dotnet build TestProcess/TestProcess.csproj
          dotnet DotnetBackground run --out reports/cmdline --project TestProcess/TestProcess.csproj --framework ${{ matrix.dotnet-version }} --no-restore
          dotnet DotnetBackground run --out reports/cmdline --project TestProcess/TestProcess.csproj --framework ${{ matrix.dotnet-version }} --no-restore --name CustomNamed ab cd
          sleep 5
          dotnet DotnetBackground kill --out reports/cmdline

      #Shows error message in case of some failure (as test report checks are not always produced)
      - name: Failure message if needed
        if: failure()
        run: echo "::error ::There was a build error or test failure, see the log and diff files in the test report artifacts"

      #prevents execution on PR or dependabot that fails with "Resource not accessible by integration" due to permissions
      - name: Publish test report
        if: ${{ always() && github.actor=='javiertuya' }} 
        uses: dorny/test-reporter@v1
        with:
          name: test-report-${{ matrix.dotnet-version }}
          path: reports/nunit/dotnet-background-report.trx
          reporter: dotnet-trx
          fail-on-error: 'true'

      - name: Publish test report files
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-${{ matrix.dotnet-version }}
          path: reports
