name: Test
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
    tags-ignore:
      - 'v*' #avoids rerun existing commit on release
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ['netcoreapp3.1', 'net5.0', 'net6.0' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      #requires all sdks to compile and run, but tests and process will be exeucuted on each matrix framework
      - uses: actions/setup-dotnet@v2
        with:
            dotnet-version: |
              3.1.x
              5.0.x
              6.0.x
      - name: Run test from project
        run: |
          dotnet build TestProcess/TestProcess.csproj
          dotnet test --framework ${{ matrix.framework }} --logger "trx;LogFileName=../../reports/nunit/dotnet-background-report.trx" TestDotnetBackground/TestDotnetBackground.csproj

      - name: Run test from commandline
        if: always()
        run: |
          dotnet new tool-manifest
          dotnet pack DotnetBackground/DotnetBackground.csproj
          dotnet tool install --no-cache --add-source DotnetBackground/nupkg DotnetBackground
          dotnet build TestProcess/TestProcess.csproj
          dotnet DotnetBackground run --out reports/cmdline --project TestProcess/TestProcess.csproj --framework ${{ matrix.framework }} --no-restore
          dotnet DotnetBackground run --out reports/cmdline --project TestProcess/TestProcess.csproj --framework ${{ matrix.framework }} --no-restore --name CustomNamed ab cd
          sleep 5
          dotnet DotnetBackground kill --out reports/cmdline

      #Shows error message in case of some failure (as test report checks are not always produced)
      - name: Failure message if needed
        if: failure()
        run: echo "::error ::There was a build error or test failure, see the log and diff files in the test report artifacts"

      #prevents execution on PR or dependabot that fails with "Resource not accessible by integration" due to permissions
      - name: Publish test report
        if: ${{ always() && github.actor=='javiertuya' }} 
        uses: dorny/test-reporter@v1
        with:
          name: test-report-${{ matrix.framework }}
          path: reports/nunit/dotnet-background-report.trx
          reporter: dotnet-trx
          fail-on-error: 'true'

      - name: Publish test report files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.framework }}
          path: reports
